### ISSUE TITLE
Landing on planets

### ISSUE THREAD

**Issue by jacobselg** [holgersson1988/EventHorizon#2]

**Comment by holgersson1988** [comment]
Fixed collision, now on to landing

**Comment by holgersson1988** [comment]
Landing fixed, need to handle rotation on the planet. And a bug at takeoff, where you can go through the planet if the thrust is larger than the gravity. Need to check direction of thrust and gravity for takeoff-check!

**Comment by holgersson1988** [comment]
Manual landing and liftoff working
